var ingredients = [
    {name:"almond extract"},
    {name:"almonds"},
    {name:"almond milk"},
    {name:"anchovies"},
    {name:"aniseed"},
    {name:"apple"},
    {name:"apple juice"},
    {name:"apricot"},
    {name:"artichoke"},
    {name:"artichoke hearts"},
    {name:"asparagus"},
    {name:"avocado"},
    {name:"bacon"},
    {name:"baking powder"},
    {name:"baking soda"},
    {name:"balsamic"},
    {name:"banana"},
    {name:"barbecue sauce"},
    {name:"basil"},
    {name:"beans"},
    {name:"beef"},
    {name:"beets"},
    {name:"bell pepper"},
    {name:"berries"},
    {name:"blackberries"},
    {name:"blueberries"},
    {name:"black beans"},
    {name:"black pepper"},
    {name:"bouillon"},
    {name:"bread"},
    {name:"broccoli"},
    {name:"brown rice"},
    {name:"brown sugar"},
    {name:"brussels sprouts"},
    {name:"butter"},
    {name:"butterbeer"},
    {name:"buttermilk"},
    {name:"cabbage"},
    {name:"cake mix"},
    {name:"cajun spice"},
    {name:"cantaloupe"},
    {name:"cardamom"},
    {name:"carrots"},
    {name:"cauliflower"},
    {name:"cayenne pepper"},
    {name:"celery"},
    {name:"cereal"},
    {name:"cheese"},
    {name:"cherries"},
    {name:"chicken"},
    {name:"chickpeas"},
    {name:"chili powder"},
    {name:"chips"},
    {name:"chives"},
    {name:"chocolate"},
    {name:"chocolate chips"},
    {name:"chorus fruit"},
    {name:"cilantro"},
    {name:"cinnamon"},
    {name:"clams"},
    {name:"cloves"},
    {name:"cocoa powder"},
    {name:"coconut"},
    {name:"coconut milk"},
    {name:"coconut oil"},
    {name:"coffee"},
    {name:"coriander"},
    {name:"corn"},
    {name:"cornmeal"},
    {name:"corn starch"},
    {name:"corn syrup"},
    {name:"couscous"},
    {name:"cranberries"},
    {name:"cream"},
    {name:"cream cheese"},
    {name:"cream of mushroom soup"},
    {name:"cream of tartar"},
    {name:"cucumber"},
    {name:"cumin"},
    {name:"curry paste"},
    {name:"curry powder"},
    {name:"dill"},
    {name:"duck"},
    {name:"egg"},
    {name:"eggplant"},
    {name:"evaporated milk"},
    {name:"fig"},
    {name:"flour"},
    {name:"food coloring"},
    {name:"french bread"},
    {name:"fruit snacks"},
    {name:"garlic"},
    {name:"garlic powder"},
    {name:"gillyweed"},
    {name:"ginger"},
    {name:"gold"},
    {name:"grapes"},
    {name:"grape juice"},
    {name:"grapefruit"},
    {name:"green beans"},
    {name:"green olive"},
    {name:"ground beef"},
    {name:"habenero peppers"},
    {name:"ham"},
    {name:"hazelnut"},
    {name:"hersheys kisses"},
    {name:"heavy cream"},
    {name:"hoisin"},
    {name:"honey"},
    {name:"hot dog"},
    {name:"ice cream"},
    {name:"jam"},
    {name:"jalapeno peppers"},
    {name:"jelly"},
    {name:"kale"},
    {name:"ketchup"},
    {name:"kiwi"},
    {name:"kidney beans"},
    {name:"leeks"},
    {name:"lembas bread"},
    {name:"lemon"},
    {name:"lemon juice"},
    {name:"lentils"},
    {name:"lettuce"},
    {name:"lime juice"},
    {name:"mango"},
    {name:"maple syrup"},
    {name:"marinara"},
    {name:"marshmallows"},
    {name:"mayonnaise"},
    {name:"milk"},
    {name:"mint"},
    {name:"mixed vegetables"},
    {name:"molasses"},
    {name:"moo pop"},
    {name:"mozzarella"},
    {name:"mushrooms"},
    {name:"mustard"},
    {name:"nutmeg"},
    {name:"nuts"},
    {name:"oats"},
    {name:"oil"},
    {name:"okra"},
    {name:"olive oil"},
    {name:"olives"},
    {name:"onion"},
    {name:"onion powder"},
    {name:"orange"},
    {name:"oregano"},
    {name:"paprika"},
    {name:"parmesan"},
    {name:"parsley"},
    {name:"pasta"},
    {name:"peach"},
    {name:"peanut butter"},
    {name:"peanuts"},
    {name:"pear"},
    {name:"peas"},
    {name:"pecans"},
    {name:"pepper"},
    {name:"pesto"},
    {name:"pineapple"},
    {name:"pinto beans"},
    {name:"pork"},
    {name:"potatoes"},
    {name:"powdered sugar"},
    {name:"protein powder"},
    {name:"pumpkin"},
    {name:"quinoa"},
    {name:"radish"},
    {name:"raisins"},
    {name:"ramen"},
    {name:"ranch"},
    {name:"raspberries"},
    {name:"refried beans"},
    {name:"rice"},
    {name:"ricotta"},
    {name:"rhubarb"},
    {name:"romaine lettuce"},
    {name:"rosemary"},
    {name:"salmon"},
    {name:"salsa"},
    {name:"salt"},
    {name:"sausage"},
    {name:"sea weed"},
    {name:"serrano pepper"},
    {name:"sesame oil"},
    {name:"shortening"},
    {name:"shrimp"},
    {name:"snap peas"},
    {name:"snozzcumbers"},
    {name:"sour cream"},
    {name:"soy sauce"},
    {name:"spinach"},
    {name:"sprinkles"},
    {name:"squash"},
    {name:"steel cut oats"},
    {name:"strawberries"},
    {name:"sugar"},
    {name:"sunflower seeds"},
    {name:"sweetened condensed milk"},
    {name:"sweet potatoes"},
    {name:"syrup"},
    {name:"tea"},
    {name:"thyme"},
    {name:"tilapia"},
    {name:"tofu"},
    {name:"tomatillos"},
    {name:"tomatoes"},
    {name:"tomato paste"},
    {name:"tomato sauce"},
    {name:"tomato soup"},
    {name:"tortillas"},
    {name:"tortilla chips"},
    {name:"tuna fish"},
    {name:"turkey"},
    {name:"turnips"},
    {name:"vanilla"},
    {name:"vegetable oil"},
    {name:"vinegar"},
    {name:"walnuts"},
    {name:"water"},
    {name:"watermelon"},
    {name:"wine"},
    {name:"whipped cream"},
    {name:"worcestershire"},
    {name:"yeast"},
    {name:"yogurt"},
    {name:"zucchini"},
]

const ingredientsIndex = []
for (let i in ingredients) {
    ingredientsIndex.push(ingredients[i].name)
}


var recipes = [
    {
        name:"Autumn Soup", 
        ingredients:["ground beef", "onion", "carrots", "potatoes", "black pepper", "basil", "tomatoes", "bouillon"],
        pre:["1 lb.", "1 Cup chopped", "1 Cup", "1 Cup cubed", "1/4 tsp.", "1/4 tsp", "28 oz.", "1 tsp."], 
        instructions:"Cook onions and ground beef. Mix in everything else as well as 3 Cups of water.",
        optional:["salt", "celery","sweet potatoes"],
        tags:["dinner", "soup", "savory"],
    },
     {
        name:"Banana Bread", 
        ingredients:["sugar", "shortening", "egg", "flour", "salt", "baking soda", "banana"], 
        pre:[ "1 cup", "1/2 cup", "2", "2 cups", "1/2 tsp.", "1 tsp.", "4 mashed"],
        instructions:"Cream sugar and shortening, add eggs, drys, bananas, and optional nuts. Bake 1 hour at 325 degrees in a 13x14 loaf pan, or less in two smaller pans",
        optional:["nuts"],
        tags:["sweet", "baking"],
    },
    {
        name:"Beans (Black) & Rice", 
        ingredients:["black beans", "rice"],
        pre:["", ""], 
        instructions:"Cook both and serve with desired toppings",
        optional:["salt", "tomatoes", "cheese", "lettuce"],
        tags:["easy", "savory"],
    },
     {
        name:"Biscuits", 
        ingredients:["flour", "salt", "baking soda", "baking powder", "butter", "milk", "vinegar"], 
        pre:[ "2 cups", "1/2 teaspoon", "1/2 teaspoon", "1 1/2 teaspoon", "1/2 cups", "1/2 cup", "1 Tablespoon"],
        instructions:"Combine dry ingredients, then cut butter in. Add vinegar to milk -can substitute lemon juice for vinegar- mix in. Knead 10 times, shape and place on cookie sheet. Bake at 450 degrees until golden.",
        tags:["baking", "bread"],
    },
     {
        name:"Bread", 
        ingredients:["yeast", "brown sugar", "shortening", "salt", "flour"], 
        pre:[ "1 Tablespoon", "1/2 cup", "1/3 cup", "1 Tablespoon", "6-8 Cups"],
        instructions:"Soften yeast in 3/4 cups water, heat remaining 2 cups of water shortening sugar and salt. Add to 3 cups flour and yeast with water, then add remaining flour incrementally as needed, knead, rise until double, shape, let rise, then bake at 350 degrees for 50 minutes.",
        tags:["baking"],
    },
     {
        name:"Bread Sticks", 
        ingredients:["yeast", "milk", "honey", "salt", "flour"], 
        pre:[ "1 T.", "1/4 cup", "1 T.", "1 tsp.", "4- 4 1/2 cups"],
        instructions:"Dissolve yeast in 1 1/4 cups warm water, stir in everything but flour, mix well. Gradually add flour until dough forms a ball, then knead lightly and shape into desired breadsticks. Place on greased cookie sheet, sprinkle with melted butter and seasonings if desired. allow to rise for 15-20 minutes, then bake at 400 degrees for 15 minutes",
        optional:["garlic", "parmesan", "butter", "onion powder"],
        tags:["bread", "baking"],
    },
     {
        name:"Brownie Pudding Cake", 
        ingredients:["flour", "baking powder", "sugar", "salt", "cocoa powder", "milk", "vegetable oil", "vanilla", "brown sugar", "cocoa powder"], 
        pre:[ "2 cups", "4 tsp.", "1 1/2 cup", "1 tsp.", "4 T.", "1 cup", "4 T.", "2 tsp.", "1 1/4 cup", "1/3 cup"],
        instructions:"Mix together the flour, baking powder, sugar, salt, cocoa powder, milk, oil, and vanilla, pour into a greased 10x14 pan. Then mix together brown sugar and 1/3 cup cocoa powder, sprinkle over top of batter in pan. Pour 3 1/2 cups boiling water over the top- DO NOT MIX! Bake at 350 degrees about 45 minutes.",
        optional:["nuts"],
        tags:["dessert", "baking", "sweet"],
        source:"Grandma Deanna Slade"
    },
    {
        name:"Crepes (easy)", 
        ingredients:["flour", "milk", "egg", "oil"],
        pre:["1 Cup", "1 1/2 Cup", "2", "1 T"], 
        instructions:"Blend in blender. Pour 1/4 cup or so onto a buttered frying pan.",
        tags:["breakfast", "easy"],
    },
    {
        name:"Crepes (fancy)", 
        ingredients:["milk", "oil", "egg", "flour", "sugar", "baking powder", "salt"],
        pre:["2 Cups", "2 T", "2", "1 1/2 Cups", "1 T", "1/2 tsp.", "1/2 tsp."],
        instructions:"Blend in blender. Pour 1/4 cup or so onto a buttered frying pan.",
        tags:["breakfast"],
    },
     {
        name:"Chicken Divan", 
        ingredients:["chicken", "rice", "broccoli", "mayonnaise", "cream of mushroom soup", "cheese", "lemon juice", "curry powder", "parmesan"], 
        pre:[ "2-3 lb, cooked and cubed", "4 cups cooked", "3 cups cooked", "1/2 cup", "1 can", "1/2 cup grated", "3-4 T.", "2 T", "1/4 cup grated"],
        instructions:"lay rice in 9x13 pan, cover with chicken and brocoli. Mix together sauce and spread next, with grated cheese on top. Bake at 350 degrees for 30 min or until bubbly",
        tags:["dinner", "casserole", "savory"],
    },
    {
        name:"Curry (Thai)", 
        ingredients:["curry paste", "coconut milk", "carrots", "potatoes", "chicken", "onion", "rice"],
        pre:["1 can", "2 cans", "4", "3", "2 breasts", "1/2 diced", ""],
        instructions:"Cook onions and chicken together then add coconut milk and 4 cups of water. Add everything and boil. Once cooked serve with rice.",
        optional:["salt", "broccoli", "pineapple"],
        tags:["dinner", "savory"],
    },
     {
        name:"Frosting", 
        ingredients:["butter", "powdered sugar", "vanilla", "milk"], 
        pre:[ "1/2 cup", "4 cups", "1 teaspoon", "3-5 T."],
        instructions:"Whip everything together",
        optional:["food coloring", "salt"],
        tags:["dessert"]
    },
    {
        name:"German Pancakes", 
        ingredients:["flour", "milk", "butter", "egg"],
        pre:["1/2 Cup", "1/2 Cup", "2 T", "3"],
        instructions:"Preheat oven to 400. Place butter in 9x13 and melt in oven. Mix well and pour into the hot buttered pan. Bake for about 25 minutes or until brown.",
        optional:["salt"],
        tags:["breakfast", "baking"],
    },
    {
        name:"Emma Noodle Sauce", 
        ingredients:["peanut butter", "soy sauce", "honey", "garlic", "ginger", "vinegar", "cayenne pepper", "hoisin"],
        pre:["1 Cup", "1/2 Cup", "1/2 Cup", "4 cloves", "1 tsp.", "2 T", "1/2 tsp.", "2 T"],
        instructions:"Mix and cook together. Server with noodles or stir fry.",
        optional:["rice", "pasta", "chicken", "mixed vegetables", "peanuts"],
        tags:["dinner", "savory"],
    },
    {
        name:"Potato Soup", 
        ingredients:["onion", "carrots", "potatoes", "bouillon", "flour", "milk", "heavy cream"], 
        pre:[ "1 diced", "5 diced", "10 diced", "12 tsp.", "5 T", "1 Cup", "2 Cups"],
        instructions:"Fry bacon until crisp, remove bacon and pour out most of the grease. Add onions carrots and celery and stir fry in remaining bacon grease for 5 min. In soup pot add broth, potatoes, onions, carrots, and celery. Cook until potatoes are getting soft. Whisk together flour and milk and pour into the soup. Cook for another 5 minutes. Blend about 1/2 of the soup and mix back in. Stir in cream. Add in cheese, parsley, and spices to taste.",
        optional:["bacon", "parsley","cheese", "celery", "salt", "black pepper", "cajun spice"],
        tags:["dinner", "soup", "savory"],
        source:"Pioneer Women (Adapted)"
    },
    {
        name:"Pancakes", 
        ingredients:["flour", "milk", "sugar", "baking powder", "egg", "oil"], 
        pre:["1 Cup", "1 Cup", "1 T", "2 tsp.", "2", "1"],
        instructions:"Mix & cook.",
        optional:["vanilla", "salt"],
        tags:["breakfast"],
    },
     {
        name:"Pizza Dough", 
        ingredients:["milk", "yeast", "sugar", "salt", "shortening", "flour"], 
        pre:[ "2 cups", "1 T.", "1/4 cup", "2 tsp.", "1/4 cup", "6 cups"],
        instructions:"Mix together drys, knead in wets. Can substitute 1/4 cup olive oil for butter if decrease milk.",
        tags:["baking"],
    },
    {
        name:"Rolls", 
        ingredients:["yeast", "shortening", "sugar", "flour", "egg", "salt"],
        pre: ["1 Tablespoon", "1/4 cup", "1/2 cup", "6 1/2 - 7 cups", "1, beaten", "1 1/2 teaspoon"],
        instructions: "Soften yeast in 2 cups of warm water. Mix remaining ingredients, add yeast, and knead. Let rise, shape, let rise again. Bake at 350 degrees.",
        tags:["baking"],
    },
    {
        name:"Sheepherder Pie", 
        ingredients:["ground beef", "tomato soup", "tomato sauce", "garlic", "onion", "green beans", "potatoes", "cheese"], 
        pre:["1 lb", "1 Can", "2 Small Cans", "", "1/2 Cup Diced", "2 Cans", "5 lbs.", ""],
        instructions:"Brown hamburger, onions, and garlic. Drain. Add sauce and soup. Pour into 9x13 baking dish. Spread a layer of beans, potatoes, and then cheese. Bake at 350 for 20 minutes.",
        optional:["butter", "salt"],
        tags:["dinner", "baking", "casserole"],
    },
     {
        name:"Stake Visitors Cake", 
        ingredients:["oats", "butter", "cocoa powder", "egg", "flour", "brown sugar", "baking soda", "chocolate chips", "sugar", "salt"], 
        pre:[ "1 cup", "1/2 cup", "1 T.", "2 beaten", "1 1/2 cups", "1 cup", "1 tsp.", "1 cup", "1 cup", "1/2 tsp."],
        instructions:"Pour 1 1/2 cup boiling water over oats and butter, let rest 10 minutes. Add sugar and eggs, beat together, then add dry ingredients and half the chocolate chips. Pour into greased 9x13, sprinkle remaining chocloate chips and optional nuts on top. Bake at 350 degrees for 30-40 minutes",
        optional:["nuts"],
        tags:["dessert", "cake", "baking"],
        source:"Grandma Deanna Slade"
    },
     {
        name:"Sugar Cookies", 
        ingredients:["butter", "sugar", "vegetable oil", "egg", "sour cream", "vanilla", "almond extract", "baking soda", "salt", "flour"], 
        pre:[ "1 cup softened", "2 cups", "3/4 cup", "2", "1/4 cups", "1 tsp.", "1/2 tsp.", "1/2 tsp.", "1 tsp.", "5-6 cups"],
        instructions:"Cream butter and sugar, add oil, eggs and sour cream, mix well. Add vanilla, almond extract, baking soda and salt, combine completely. add flour slowly until not longer sticky. Shape cookies and place on ungreased baking sheet, bake at 350 degrees",
        tags:["cookies", "dessert", "baking"],
        source:"Brilynn Ellsworth"
    },
    {
        name:"Sweet Potato Fries", 
        ingredients:["sweet potatoes", "olive oil", "garlic powder", "paprika"], 
        pre:["", "2 T", "1 tsp", "1 tsp"],
        instructions:"Heat the over to 400. Peel and slice the sweet potatoes. Mix potatoes with oil and spices and lay on tray. Cook for about 10 minutes on each side or until done.",
        optional:["salt", "ketchup", "black pepper", "oil"],
        tags:["dinner", "side", "baking", "savory"],
    },
]